name = "Pages"
uuid = "7c165e09-dada-5b64-9fdc-39b801c58527"
authors = ["Eric Forgy <Eric.Forgy@coherentasia.com>"]
version = "0.3.1"

[deps]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"

[compat]
julia = "^1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
